name: Periodic

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * SUN

jobs:
  test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.10']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry for Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH
      - name: Install Poetry for OSX
        if: matrix.os == 'macos-latest'
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH
      - name: Install Poetry for Windows
        if: matrix.os == 'windows-latest'
        run: |
          (Invoke-WebRequest -Uri https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py -UseBasicParsing).Content | python
          (Resolve-Path ~/.poetry/bin).Path >> $Env:GITHUB
      # - name: Poetry Version
      #   run: |
      #     poetry --version
      - name: Install dependencies
        run: |
          poetry install --no-interaction
      - name: Run lint
        run: |
          poetry run isort --check --diff docs pyexample tests
          poetry run black --check docs pyexample tests
      - name: Run tests
        run: |
          poetry run pytest
