name: Periodic

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * SUN

jobs:
  test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.12']
        poetry-version: ["1.8.5"]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: abatilo/actions-poetry@v4
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: Install dependencies
        run: |
          poetry install --no-interaction

      - name: Run lint
        run: |
          poetry run isort --check --diff docs pyexample tests
          poetry run black --check docs pyexample tests

      - name: Type check with mypy
        run: |
          poetry run mypy ./cougerbot ./tests

      - name: Run tests
        run: |
          poetry run pytest --benchmark-skip --disable-warnings
