name: Regression

on:
  workflow_dispatch:
  push:
    paths:
      - 'pyexample/**'
      - 'tests/**'
    branches:
      - main
  pull_request:
    paths:
      - 'pyexample/**'
      - 'tests/**'
    types:
      - opened
      - synchronize

jobs:
  test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.10']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Test
        run: |
          python setup.py test

  coveralls:
    name: Coveralls
    needs: test
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.10']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Test for coverage
        run: |
          pip install coverage
          python setup.py test
          coverage run setup.py test
      - name: Coveralls
        uses: AndreMiras/coveralls-python-action@develop
        with:
          parallel: true
          flag-name: Unit Test

  coveralls_finish:
    name: Coveralls Finish
    needs: coveralls
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.10']
    runs-on: ${{ matrix.os }}
    steps:
    - name: Coveralls Finished
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel-finished: true
